import type { Metadata } from "next";
import { fonts } from "./fonts";
import { Provider } from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "Bero Studio",
    template: "%s | Bero Studio",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.poppins.variable}>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
